use_frameworks!

target 'YStaticContentTableView_Example' do
  pod 'YStaticContentTableView', :path => '../'
#  pod 'YStaticContentTableView'

  target 'YStaticContentTableView_Tests' do
    inherit! :search_paths

  end
end
